version: '3.9'
services:
  mongodb:
    image: docker.io/bitnami/mongodb
    restart: always
    container_name: microservices_mongodb
    environment:
      # MONGODB_ROOT_USER: admin
      # MONGODB_ROOT_PASSWORD: admin
      BITNAMI_DEBUG: 'false'
      ALLOW_EMPTY_PASSWORD: 'yes'
      MONGODB_SYSTEM_LOG_VERBOSITY: '0'
      MONGODB_DISABLE_SYSTEM_LOG: 'no'
      MONGODB_DISABLE_JAVASCRIPT: 'no'
      MONGODB_ENABLE_JOURNAL: 'yes'
      MONGODB_ENABLE_DIRECTORY_PER_DB: 'no'
      MONGODB_DATABASE: 'invoices'
    volumes:
      - ./mongodb_data_container:/data/db
    ports:
      - '27017:27017'
